// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-jokOwij1LHflFrlaQnI0A3yNNRwmXqg',
    appId: '1:27734595837:android:7f77f952c23a71aa99c694',
    messagingSenderId: '27734595837',
    projectId: 'football-firebase-3e1e0',
    databaseURL: 'https://football-firebase-3e1e0-default-rtdb.firebaseio.com',
    storageBucket: 'football-firebase-3e1e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH3FWAMvlN15D1zBWvrVf2zyZkolJjwdk',
    appId: '1:27734595837:ios:d852e723456731a599c694',
    messagingSenderId: '27734595837',
    projectId: 'football-firebase-3e1e0',
    databaseURL: 'https://football-firebase-3e1e0-default-rtdb.firebaseio.com',
    storageBucket: 'football-firebase-3e1e0.firebasestorage.app',
    iosBundleId: 'com.example.footballFirebase',
  );

}